package models

import "time"

type PlayByPlay struct {
	ID                           *string   `json:"id,omitempty"`
	SequenceNumber               *string   `json:"sequence_number,omitempty"`
	TypeID                       *int32    `json:"type_id,omitempty"`
	TypeText                     *string   `json:"type_text,omitempty"`
	Text                         *string   `json:"text,omitempty"`
	AwayScore                    *int32    `json:"away_score,omitempty"`
	HomeScore                    *int32    `json:"home_score,omitempty"`
	PeriodNumber                 *int32    `json:"period_number,omitempty"`
	PeriodDisplayValue           *string   `json:"period_display_value,omitempty"`
	ClockDisplayValue            *string   `json:"clock_display_value,omitempty"`
	ScoringPlay                  *bool     `json:"scoring_play,omitempty"`
	ScoreValue                   *int32    `json:"score_value,omitempty"`
	TeamID                       *int32    `json:"team_id,omitempty"`
	AthleteID1                   *int32    `json:"athlete_id_1,omitempty"`
	AthleteID2                   *int32    `json:"athlete_id_2,omitempty"`
	AthleteID3                   *int32    `json:"athlete_id_3,omitempty"`
	Wallclock                    *string   `json:"wallclock,omitempty"`
	ShootingPlay                 *bool     `json:"shooting_play,omitempty"`
	CoordinateXRaw               *string   `json:"coordinate_x_raw,omitempty"`
	CoordinateYRaw               *string   `json:"coordinate_y_raw,omitempty"`
	PointsAttempted              *int32    `json:"points_attempted,omitempty"`
	ShortDescription             *string   `json:"short_description,omitempty"`
	Season                       *int32    `json:"season,omitempty"`
	SeasonType                   *int32    `json:"season_type,omitempty"`
	AwayTeamID                   *int32    `json:"away_team_id,omitempty"`
	AwayTeamName                 *string   `json:"away_team_name,omitempty"`
	AwayTeamMascot               *string   `json:"away_team_mascot,omitempty"`
	AwayTeamAbbrev               *string   `json:"away_team_abbrev,omitempty"`
	AwayTeamNameAlt              *string   `json:"away_team_name_alt,omitempty"`
	HomeTeamID                   *int32    `json:"home_team_id,omitempty"`
	HomeTeamName                 *string   `json:"home_team_name,omitempty"`
	HomeTeamMascot               *string   `json:"home_team_mascot,omitempty"`
	HomeTeamAbbrev               *string   `json:"home_team_abbrev,omitempty"`
	HomeTeamNameAlt              *string   `json:"home_team_name_alt,omitempty"`
	HomeTeamSpread               *string   `json:"home_team_spread,omitempty"`
	GameSpread                   *string   `json:"game_spread,omitempty"`
	HomeFavorite                 *bool     `json:"home_favorite,omitempty"`
	GameSpreadAvailable          *bool     `json:"game_spread_available,omitempty"`
	GameID                       *int64    `json:"game_id,omitempty"`
	Qtr                          *int32    `json:"qtr,omitempty"`
	Time                         *string   `json:"time,omitempty"`
	ClockMinutes                 *int32    `json:"clock_minutes,omitempty"`
	ClockSeconds                 *string   `json:"clock_seconds,omitempty"`
	Half                         *string   `json:"half,omitempty"`
	GameHalf                     *string   `json:"game_half,omitempty"`
	LeadQtr                      *int32    `json:"lead_qtr,omitempty"`
	LeadGameHalf                 *string   `json:"lead_game_half,omitempty"`
	LeadHalf                     *string   `json:"lead_half,omitempty"`
	StartQuarterSecondsRemaining *string   `json:"start_quarter_seconds_remaining,omitempty"`
	StartHalfSecondsRemaining    *string   `json:"start_half_seconds_remaining,omitempty"`
	StartGameSecondsRemaining    *string   `json:"start_game_seconds_remaining,omitempty"`
	GamePlayNumber               *int32    `json:"game_play_number,omitempty"`
	EndQuarterSecondsRemaining   *string   `json:"end_quarter_seconds_remaining,omitempty"`
	EndHalfSecondsRemaining      *string   `json:"end_half_seconds_remaining,omitempty"`
	EndGameSecondsRemaining      *string   `json:"end_game_seconds_remaining,omitempty"`
	Period                       *int32    `json:"period,omitempty"`
	LagQtr                       *int32    `json:"lag_qtr,omitempty"`
	LagGameHalf                  *string   `json:"lag_game_half,omitempty"`
	LagHalf                      *string   `json:"lag_half,omitempty"`
	CoordinateX                  *string   `json:"coordinate_x,omitempty"`
	CoordinateY                  *string   `json:"coordinate_y,omitempty"`
	GameDate                     *time.Time `json:"game_date,omitempty"`
	GameDateTime                 *time.Time `json:"game_date_time,omitempty"`
	TypeAbbreviation             *string   `json:"type_abbreviation,omitempty"`
	HomeTimeoutCalled            *bool     `json:"home_timeout_called,omitempty"`
	AwayTimeoutCalled            *bool     `json:"away_timeout_called,omitempty"`
}
