-- Player box scores raw: schema matches hoopR load_nba_player_box() output
-- Used by nba_data_collection.R (loads CSV from hoopR into this table)
CREATE TABLE player_boxscores_raw (
  game_id BIGINT NOT NULL,
  season INTEGER NOT NULL,
  season_type INTEGER NOT NULL,
  game_date DATE NOT NULL,
  game_date_time TIMESTAMPTZ NOT NULL,
  athlete_id BIGINT NOT NULL,
  athlete_display_name TEXT NOT NULL,
  team_id BIGINT NOT NULL,
  team_name TEXT NOT NULL,
  team_location TEXT NOT NULL,
  team_short_display_name TEXT NOT NULL,
  minutes NUMERIC,
  field_goals_made INTEGER,
  field_goals_attempted INTEGER,
  three_point_field_goals_made INTEGER,
  three_point_field_goals_attempted INTEGER,
  free_throws_made INTEGER,
  free_throws_attempted INTEGER,
  offensive_rebounds INTEGER,
  defensive_rebounds INTEGER,
  rebounds INTEGER,
  assists INTEGER,
  steals INTEGER,
  blocks INTEGER,
  turnovers INTEGER,
  fouls INTEGER,
  plus_minus TEXT,
  points INTEGER,
  starter BOOLEAN,
  ejected BOOLEAN,
  did_not_play BOOLEAN,
  reason TEXT,
  active BOOLEAN,
  athlete_jersey TEXT,
  athlete_short_name TEXT,
  athlete_headshot_href TEXT,
  athlete_position_name TEXT,
  athlete_position_abbreviation TEXT,
  team_display_name TEXT NOT NULL,
  team_uid TEXT NOT NULL,
  team_slug TEXT NOT NULL,
  team_logo TEXT NOT NULL,
  team_abbreviation TEXT NOT NULL,
  team_color TEXT NOT NULL,
  team_alternate_color TEXT NOT NULL,
  home_away TEXT NOT NULL,
  team_winner BOOLEAN NOT NULL,
  team_score INTEGER NOT NULL,
  opponent_team_id BIGINT NOT NULL,
  opponent_team_name TEXT,
  opponent_team_location TEXT,
  opponent_team_display_name TEXT,
  opponent_team_abbreviation TEXT,
  opponent_team_logo TEXT,
  opponent_team_color TEXT,
  opponent_team_alternate_color TEXT,
  opponent_team_score INTEGER
);

-- Indexes for common filters (same as R script STEP 6)
CREATE INDEX IF NOT EXISTS idx_player_boxscores_raw_athlete_id ON player_boxscores_raw (athlete_id);
CREATE INDEX IF NOT EXISTS idx_player_boxscores_raw_game_date ON player_boxscores_raw (game_date);
CREATE INDEX IF NOT EXISTS idx_player_boxscores_raw_team_id ON player_boxscores_raw (team_id);
CREATE INDEX IF NOT EXISTS idx_player_boxscores_raw_season ON player_boxscores_raw (season);
