-- NBA hoopR tables: schemas match load_nba_player_box, load_nba_pbp, load_nba_team_box, load_nba_schedule
-- Used by nba_data_to_db.R.r

-- Player box scores raw
CREATE TABLE player_boxscores_raw (
  game_id BIGINT NOT NULL,
  season INTEGER NOT NULL,
  season_type INTEGER NOT NULL,
  game_date DATE NOT NULL,
  game_date_time TIMESTAMPTZ NOT NULL,
  athlete_id BIGINT NOT NULL,
  athlete_display_name TEXT NOT NULL,
  team_id BIGINT NOT NULL,
  team_name TEXT NOT NULL,
  team_location TEXT NOT NULL,
  team_short_display_name TEXT NOT NULL,
  minutes NUMERIC,
  field_goals_made INTEGER,
  field_goals_attempted INTEGER,
  three_point_field_goals_made INTEGER,
  three_point_field_goals_attempted INTEGER,
  free_throws_made INTEGER,
  free_throws_attempted INTEGER,
  offensive_rebounds INTEGER,
  defensive_rebounds INTEGER,
  rebounds INTEGER,
  assists INTEGER,
  steals INTEGER,
  blocks INTEGER,
  turnovers INTEGER,
  fouls INTEGER,
  plus_minus TEXT,
  points INTEGER,
  starter BOOLEAN,
  ejected BOOLEAN,
  did_not_play BOOLEAN,
  reason TEXT,
  active BOOLEAN,
  athlete_jersey TEXT,
  athlete_short_name TEXT,
  athlete_headshot_href TEXT,
  athlete_position_name TEXT,
  athlete_position_abbreviation TEXT,
  team_display_name TEXT,
  team_uid TEXT,
  team_slug TEXT,
  team_logo TEXT,
  team_abbreviation TEXT,
  team_color TEXT,
  team_alternate_color TEXT,
  home_away TEXT,
  team_winner BOOLEAN,
  team_score INTEGER,
  opponent_team_id BIGINT,
  opponent_team_name TEXT,
  opponent_team_location TEXT,
  opponent_team_display_name TEXT,
  opponent_team_abbreviation TEXT,
  opponent_team_logo TEXT,
  opponent_team_color TEXT,
  opponent_team_alternate_color TEXT,
  opponent_team_score INTEGER
);
CREATE INDEX IF NOT EXISTS idx_player_boxscores_raw_athlete_id ON player_boxscores_raw (athlete_id);
CREATE INDEX IF NOT EXISTS idx_player_boxscores_raw_game_date ON player_boxscores_raw (game_date);
CREATE INDEX IF NOT EXISTS idx_player_boxscores_raw_team_id ON player_boxscores_raw (team_id);
CREATE INDEX IF NOT EXISTS idx_player_boxscores_raw_season ON player_boxscores_raw (season);

-- Play-by-play raw (64 columns per hoopR load_nba_pbp)
CREATE TABLE play_by_play_raw (
  id NUMERIC,
  sequence_number TEXT,
  type_id INTEGER,
  type_text TEXT,
  text TEXT,
  away_score INTEGER,
  home_score INTEGER,
  period_number INTEGER,
  period_display_value TEXT,
  clock_display_value TEXT,
  scoring_play BOOLEAN,
  score_value INTEGER,
  team_id INTEGER,
  athlete_id_1 INTEGER,
  athlete_id_2 INTEGER,
  athlete_id_3 INTEGER,
  wallclock TEXT,
  shooting_play BOOLEAN,
  coordinate_x_raw NUMERIC,
  coordinate_y_raw NUMERIC,
  points_attempted INTEGER,
  short_description TEXT,
  season INTEGER,
  season_type INTEGER,
  away_team_id INTEGER,
  away_team_name TEXT,
  away_team_mascot TEXT,
  away_team_abbrev TEXT,
  away_team_name_alt TEXT,
  home_team_id INTEGER,
  home_team_name TEXT,
  home_team_mascot TEXT,
  home_team_abbrev TEXT,
  home_team_name_alt TEXT,
  home_team_spread NUMERIC,
  game_spread NUMERIC,
  home_favorite BOOLEAN,
  game_spread_available BOOLEAN,
  game_id BIGINT,
  qtr INTEGER,
  time TEXT,
  clock_minutes INTEGER,
  clock_seconds NUMERIC,
  half TEXT,
  game_half TEXT,
  lead_qtr INTEGER,
  lead_game_half TEXT,
  lead_half TEXT,
  start_quarter_seconds_remaining NUMERIC,
  start_half_seconds_remaining NUMERIC,
  start_game_seconds_remaining NUMERIC,
  game_play_number INTEGER,
  end_quarter_seconds_remaining NUMERIC,
  end_half_seconds_remaining NUMERIC,
  end_game_seconds_remaining NUMERIC,
  period INTEGER,
  lag_qtr INTEGER,
  lag_game_half TEXT,
  lag_half TEXT,
  coordinate_x NUMERIC,
  coordinate_y NUMERIC,
  game_date DATE,
  game_date_time TIMESTAMPTZ,
  type_abbreviation TEXT,
  home_timeout_called BOOLEAN,
  away_timeout_called BOOLEAN
);
CREATE INDEX IF NOT EXISTS idx_play_by_play_raw_game_id ON play_by_play_raw (game_id);
CREATE INDEX IF NOT EXISTS idx_play_by_play_raw_game_date ON play_by_play_raw (game_date);
CREATE INDEX IF NOT EXISTS idx_play_by_play_raw_season ON play_by_play_raw (season);

-- Team box scores raw
CREATE TABLE team_boxscores_raw (
  game_id BIGINT NOT NULL,
  season INTEGER NOT NULL,
  season_type INTEGER NOT NULL,
  game_date DATE NOT NULL,
  game_date_time TIMESTAMPTZ NOT NULL,
  team_id BIGINT NOT NULL,
  team_uid TEXT,
  team_slug TEXT,
  team_location TEXT,
  team_name TEXT,
  team_abbreviation TEXT,
  team_display_name TEXT,
  team_short_display_name TEXT,
  team_color TEXT,
  team_alternate_color TEXT,
  team_logo TEXT,
  team_home_away TEXT,
  team_score INTEGER,
  team_winner BOOLEAN,
  assists INTEGER,
  blocks INTEGER,
  defensive_rebounds INTEGER,
  disqualifications INTEGER,
  ejections INTEGER,
  fast_break_points TEXT,
  field_goal_pct NUMERIC,
  field_goals_made INTEGER,
  field_goals_attempted INTEGER,
  flagrant_fouls INTEGER,
  fouls INTEGER,
  free_throw_pct NUMERIC,
  free_throws_made INTEGER,
  free_throws_attempted INTEGER,
  largest_lead TEXT,
  lead_changes INTEGER,
  lead_percentage NUMERIC,
  offensive_rebounds INTEGER,
  points_in_paint TEXT,
  steals INTEGER,
  team_turnovers INTEGER,
  technical_fouls INTEGER,
  three_point_field_goal_pct NUMERIC,
  three_point_field_goals_made INTEGER,
  three_point_field_goals_attempted INTEGER,
  times_tied INTEGER,
  total_rebounds INTEGER,
  total_technical_fouls INTEGER,
  total_turnovers INTEGER,
  turnover_points TEXT,
  turnovers INTEGER,
  opponent_team_id BIGINT,
  opponent_team_uid TEXT,
  opponent_team_slug TEXT,
  opponent_team_location TEXT,
  opponent_team_name TEXT,
  opponent_team_abbreviation TEXT,
  opponent_team_display_name TEXT,
  opponent_team_short_display_name TEXT,
  opponent_team_color TEXT,
  opponent_team_alternate_color TEXT,
  opponent_team_logo TEXT,
  opponent_team_score INTEGER

);

CREATE INDEX IF NOT EXISTS idx_team_boxscores_raw_team_id ON team_boxscores_raw (team_id);
CREATE INDEX IF NOT EXISTS idx_team_boxscores_raw_game_date ON team_boxscores_raw (game_date);
CREATE INDEX IF NOT EXISTS idx_team_boxscores_raw_game_id ON team_boxscores_raw (game_id);
CREATE INDEX IF NOT EXISTS idx_team_boxscores_raw_season ON team_boxscores_raw (season);

-- Schedules
CREATE TABLE schedules (
  id INTEGER,
  uid TEXT,
  date TEXT,
  attendance INTEGER,
  time_valid BOOLEAN,
  neutral_site BOOLEAN,
  conference_competition BOOLEAN,
  recent BOOLEAN,
  start_date TEXT,
  notes_type TEXT,
  notes_headline TEXT,
  type_id INTEGER,
  type_abbreviation TEXT,
  venue_id INTEGER,
  venue_full_name TEXT,
  venue_address_city TEXT,
  venue_capacity INTEGER,
  venue_indoor BOOLEAN,
  status_clock INTEGER,
  status_display_clock TEXT,
  status_period INTEGER,
  status_type_id INTEGER,
  status_type_name TEXT,
  status_type_state TEXT,
  status_type_completed BOOLEAN,
  status_type_description TEXT,
  status_type_detail TEXT,
  status_type_short_detail TEXT,
  format_regulation_periods INTEGER,
  home_id INTEGER,
  home_uid TEXT,
  home_location TEXT,
  home_name TEXT,
  home_abbreviation TEXT,
  home_display_name TEXT,
  home_short_display_name TEXT,
  home_color TEXT,
  home_alternate_color TEXT,
  home_is_active BOOLEAN,
  home_venue_id INTEGER,
  home_logo TEXT,
  home_score INTEGER,
  home_winner BOOLEAN,
  away_id INTEGER,
  away_uid TEXT,
  away_location TEXT,
  away_name TEXT,
  away_abbreviation TEXT,
  away_display_name TEXT,
  away_short_display_name TEXT,
  away_color TEXT,
  away_alternate_color TEXT,
  away_is_active BOOLEAN,
  away_venue_id INTEGER,
  away_logo TEXT,
  away_score INTEGER,
  away_winner BOOLEAN,
  game_id BIGINT,
  season INTEGER,
  season_type INTEGER,
  venue_address_state TEXT,
  status_type_alt_detail TEXT,
  "PBP" TEXT,
  team_box BOOLEAN,
  player_box BOOLEAN,
  game_date_time TIMESTAMPTZ,
  game_date DATE,
  play_by_play_available BOOLEAN,
  broadcast TEXT, 
  highlights TEXT, 
  broadcast_market TEXT, 
  broadcast_name TEXT,
  home_linescores TEXT, 
  home_records TEXT, 
  away_linescores TEXT, 
  away_records TEXT, 
  game_json JSONB,
  game_json_url TEXT
);
CREATE INDEX IF NOT EXISTS idx_schedules_game_id ON schedules (game_id);
CREATE INDEX IF NOT EXISTS idx_schedules_game_date ON schedules (game_date);
CREATE INDEX IF NOT EXISTS idx_schedules_season ON schedules (season);
