// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type PlayerBoxscoresRaw struct {
	GameID                        int64          `json:"game_id"`
	Season                        int32          `json:"season"`
	SeasonType                    int32          `json:"season_type"`
	GameDate                      time.Time      `json:"game_date"`
	GameDateTime                  time.Time      `json:"game_date_time"`
	AthleteID                     int64          `json:"athlete_id"`
	AthleteDisplayName            string         `json:"athlete_display_name"`
	TeamID                        int64          `json:"team_id"`
	TeamName                      string         `json:"team_name"`
	TeamLocation                  string         `json:"team_location"`
	TeamShortDisplayName          string         `json:"team_short_display_name"`
	Minutes                       sql.NullString `json:"minutes"`
	FieldGoalsMade                sql.NullInt32  `json:"field_goals_made"`
	FieldGoalsAttempted           sql.NullInt32  `json:"field_goals_attempted"`
	ThreePointFieldGoalsMade      sql.NullInt32  `json:"three_point_field_goals_made"`
	ThreePointFieldGoalsAttempted sql.NullInt32  `json:"three_point_field_goals_attempted"`
	FreeThrowsMade                sql.NullInt32  `json:"free_throws_made"`
	FreeThrowsAttempted           sql.NullInt32  `json:"free_throws_attempted"`
	OffensiveRebounds             sql.NullInt32  `json:"offensive_rebounds"`
	DefensiveRebounds             sql.NullInt32  `json:"defensive_rebounds"`
	Rebounds                      sql.NullInt32  `json:"rebounds"`
	Assists                       sql.NullInt32  `json:"assists"`
	Steals                        sql.NullInt32  `json:"steals"`
	Blocks                        sql.NullInt32  `json:"blocks"`
	Turnovers                     sql.NullInt32  `json:"turnovers"`
	Fouls                         sql.NullInt32  `json:"fouls"`
	PlusMinus                     sql.NullString `json:"plus_minus"`
	Points                        sql.NullInt32  `json:"points"`
	Starter                       sql.NullBool   `json:"starter"`
	Ejected                       sql.NullBool   `json:"ejected"`
	DidNotPlay                    sql.NullBool   `json:"did_not_play"`
	Reason                        sql.NullString `json:"reason"`
	Active                        sql.NullBool   `json:"active"`
	AthleteJersey                 sql.NullString `json:"athlete_jersey"`
	AthleteShortName              sql.NullString `json:"athlete_short_name"`
	AthleteHeadshotHref           sql.NullString `json:"athlete_headshot_href"`
	AthletePositionName           sql.NullString `json:"athlete_position_name"`
	AthletePositionAbbreviation   sql.NullString `json:"athlete_position_abbreviation"`
	TeamDisplayName               string         `json:"team_display_name"`
	TeamUid                       string         `json:"team_uid"`
	TeamSlug                      string         `json:"team_slug"`
	TeamLogo                      string         `json:"team_logo"`
	TeamAbbreviation              string         `json:"team_abbreviation"`
	TeamColor                     string         `json:"team_color"`
	TeamAlternateColor            string         `json:"team_alternate_color"`
	HomeAway                      string         `json:"home_away"`
	TeamWinner                    bool           `json:"team_winner"`
	TeamScore                     int32          `json:"team_score"`
	OpponentTeamID                int64          `json:"opponent_team_id"`
	OpponentTeamName              sql.NullString `json:"opponent_team_name"`
	OpponentTeamLocation          sql.NullString `json:"opponent_team_location"`
	OpponentTeamDisplayName       sql.NullString `json:"opponent_team_display_name"`
	OpponentTeamAbbreviation      sql.NullString `json:"opponent_team_abbreviation"`
	OpponentTeamLogo              sql.NullString `json:"opponent_team_logo"`
	OpponentTeamColor             sql.NullString `json:"opponent_team_color"`
	OpponentTeamAlternateColor    sql.NullString `json:"opponent_team_alternate_color"`
	OpponentTeamScore             sql.NullInt32  `json:"opponent_team_score"`
}
