// Code generated by sqlc. DO NOT EDIT.
// source: play_by_play.sql

package db

import (
	"context"
)

const listPlayByPlay = `-- name: ListPlayByPlay :many
SELECT id, sequence_number, type_id, type_text, text, away_score, home_score, period_number, period_display_value, clock_display_value, scoring_play, score_value, team_id, athlete_id_1, athlete_id_2, athlete_id_3, wallclock, shooting_play, coordinate_x_raw, coordinate_y_raw, points_attempted, short_description, season, season_type, away_team_id, away_team_name, away_team_mascot, away_team_abbrev, away_team_name_alt, home_team_id, home_team_name, home_team_mascot, home_team_abbrev, home_team_name_alt, home_team_spread, game_spread, home_favorite, game_spread_available, game_id, qtr, time, clock_minutes, clock_seconds, half, game_half, lead_qtr, lead_game_half, lead_half, start_quarter_seconds_remaining, start_half_seconds_remaining, start_game_seconds_remaining, game_play_number, end_quarter_seconds_remaining, end_half_seconds_remaining, end_game_seconds_remaining, period, lag_qtr, lag_game_half, lag_half, coordinate_x, coordinate_y, game_date, game_date_time, type_abbreviation, home_timeout_called, away_timeout_called FROM play_by_play_raw
ORDER BY game_date DESC, game_id, game_play_number
LIMIT $1 OFFSET $2
`

type ListPlayByPlayParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPlayByPlay(ctx context.Context, arg ListPlayByPlayParams) ([]PlayByPlayRaw, error) {
	rows, err := q.db.QueryContext(ctx, listPlayByPlay, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayByPlayRaw
	for rows.Next() {
		var i PlayByPlayRaw
		if err := rows.Scan(
			&i.ID,
			&i.SequenceNumber,
			&i.TypeID,
			&i.TypeText,
			&i.Text,
			&i.AwayScore,
			&i.HomeScore,
			&i.PeriodNumber,
			&i.PeriodDisplayValue,
			&i.ClockDisplayValue,
			&i.ScoringPlay,
			&i.ScoreValue,
			&i.TeamID,
			&i.AthleteID1,
			&i.AthleteID2,
			&i.AthleteID3,
			&i.Wallclock,
			&i.ShootingPlay,
			&i.CoordinateXRaw,
			&i.CoordinateYRaw,
			&i.PointsAttempted,
			&i.ShortDescription,
			&i.Season,
			&i.SeasonType,
			&i.AwayTeamID,
			&i.AwayTeamName,
			&i.AwayTeamMascot,
			&i.AwayTeamAbbrev,
			&i.AwayTeamNameAlt,
			&i.HomeTeamID,
			&i.HomeTeamName,
			&i.HomeTeamMascot,
			&i.HomeTeamAbbrev,
			&i.HomeTeamNameAlt,
			&i.HomeTeamSpread,
			&i.GameSpread,
			&i.HomeFavorite,
			&i.GameSpreadAvailable,
			&i.GameID,
			&i.Qtr,
			&i.Time,
			&i.ClockMinutes,
			&i.ClockSeconds,
			&i.Half,
			&i.GameHalf,
			&i.LeadQtr,
			&i.LeadGameHalf,
			&i.LeadHalf,
			&i.StartQuarterSecondsRemaining,
			&i.StartHalfSecondsRemaining,
			&i.StartGameSecondsRemaining,
			&i.GamePlayNumber,
			&i.EndQuarterSecondsRemaining,
			&i.EndHalfSecondsRemaining,
			&i.EndGameSecondsRemaining,
			&i.Period,
			&i.LagQtr,
			&i.LagGameHalf,
			&i.LagHalf,
			&i.CoordinateX,
			&i.CoordinateY,
			&i.GameDate,
			&i.GameDateTime,
			&i.TypeAbbreviation,
			&i.HomeTimeoutCalled,
			&i.AwayTimeoutCalled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
