// Code generated by sqlc. DO NOT EDIT.
// source: player_boxscore.sql

package db

import (
	"context"
)

const listAllBoxscores = `-- name: ListAllBoxscores :many
SELECT game_id, season, season_type, game_date, game_date_time, athlete_id, athlete_display_name, team_id, team_name, team_location, team_short_display_name, minutes, field_goals_made, field_goals_attempted, three_point_field_goals_made, three_point_field_goals_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, fouls, plus_minus, points, starter, ejected, did_not_play, reason, active, athlete_jersey, athlete_short_name, athlete_headshot_href, athlete_position_name, athlete_position_abbreviation, team_display_name, team_uid, team_slug, team_logo, team_abbreviation, team_color, team_alternate_color, home_away, team_winner, team_score, opponent_team_id, opponent_team_name, opponent_team_location, opponent_team_display_name, opponent_team_abbreviation, opponent_team_logo, opponent_team_color, opponent_team_alternate_color, opponent_team_score FROM player_boxscores_raw
ORDER BY game_date DESC, game_id, athlete_id
LIMIT $1 OFFSET $2
`

type ListAllBoxscoresParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllBoxscores(ctx context.Context, arg ListAllBoxscoresParams) ([]PlayerBoxscoresRaw, error) {
	rows, err := q.db.QueryContext(ctx, listAllBoxscores, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerBoxscoresRaw
	for rows.Next() {
		var i PlayerBoxscoresRaw
		if err := rows.Scan(
			&i.GameID,
			&i.Season,
			&i.SeasonType,
			&i.GameDate,
			&i.GameDateTime,
			&i.AthleteID,
			&i.AthleteDisplayName,
			&i.TeamID,
			&i.TeamName,
			&i.TeamLocation,
			&i.TeamShortDisplayName,
			&i.Minutes,
			&i.FieldGoalsMade,
			&i.FieldGoalsAttempted,
			&i.ThreePointFieldGoalsMade,
			&i.ThreePointFieldGoalsAttempted,
			&i.FreeThrowsMade,
			&i.FreeThrowsAttempted,
			&i.OffensiveRebounds,
			&i.DefensiveRebounds,
			&i.Rebounds,
			&i.Assists,
			&i.Steals,
			&i.Blocks,
			&i.Turnovers,
			&i.Fouls,
			&i.PlusMinus,
			&i.Points,
			&i.Starter,
			&i.Ejected,
			&i.DidNotPlay,
			&i.Reason,
			&i.Active,
			&i.AthleteJersey,
			&i.AthleteShortName,
			&i.AthleteHeadshotHref,
			&i.AthletePositionName,
			&i.AthletePositionAbbreviation,
			&i.TeamDisplayName,
			&i.TeamUid,
			&i.TeamSlug,
			&i.TeamLogo,
			&i.TeamAbbreviation,
			&i.TeamColor,
			&i.TeamAlternateColor,
			&i.HomeAway,
			&i.TeamWinner,
			&i.TeamScore,
			&i.OpponentTeamID,
			&i.OpponentTeamName,
			&i.OpponentTeamLocation,
			&i.OpponentTeamDisplayName,
			&i.OpponentTeamAbbreviation,
			&i.OpponentTeamLogo,
			&i.OpponentTeamColor,
			&i.OpponentTeamAlternateColor,
			&i.OpponentTeamScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
