// Code generated by sqlc. DO NOT EDIT.
// source: schedules.sql

package db

import (
	"context"
)

const listSchedules = `-- name: ListSchedules :many
SELECT id, uid, date, attendance, time_valid, neutral_site, conference_competition, recent, start_date, notes_type, notes_headline, type_id, type_abbreviation, venue_id, venue_full_name, venue_address_city, venue_capacity, venue_indoor, status_clock, status_display_clock, status_period, status_type_id, status_type_name, status_type_state, status_type_completed, status_type_description, status_type_detail, status_type_short_detail, format_regulation_periods, home_id, home_uid, home_location, home_name, home_abbreviation, home_display_name, home_short_display_name, home_color, home_alternate_color, home_is_active, home_venue_id, home_logo, home_score, home_winner, away_id, away_uid, away_location, away_name, away_abbreviation, away_display_name, away_short_display_name, away_color, away_alternate_color, away_is_active, away_venue_id, away_logo, away_score, away_winner, game_id, season, season_type, venue_address_state, status_type_alt_detail, "PBP", team_box, player_box, game_date_time, game_date, play_by_play_available, broadcast, highlights, broadcast_market, broadcast_name, home_linescores, home_records, away_linescores, away_records, game_json, game_json_url FROM schedules
ORDER BY game_date DESC, game_id
LIMIT $1 OFFSET $2
`

type ListSchedulesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSchedules(ctx context.Context, arg ListSchedulesParams) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedules, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.Date,
			&i.Attendance,
			&i.TimeValid,
			&i.NeutralSite,
			&i.ConferenceCompetition,
			&i.Recent,
			&i.StartDate,
			&i.NotesType,
			&i.NotesHeadline,
			&i.TypeID,
			&i.TypeAbbreviation,
			&i.VenueID,
			&i.VenueFullName,
			&i.VenueAddressCity,
			&i.VenueCapacity,
			&i.VenueIndoor,
			&i.StatusClock,
			&i.StatusDisplayClock,
			&i.StatusPeriod,
			&i.StatusTypeID,
			&i.StatusTypeName,
			&i.StatusTypeState,
			&i.StatusTypeCompleted,
			&i.StatusTypeDescription,
			&i.StatusTypeDetail,
			&i.StatusTypeShortDetail,
			&i.FormatRegulationPeriods,
			&i.HomeID,
			&i.HomeUid,
			&i.HomeLocation,
			&i.HomeName,
			&i.HomeAbbreviation,
			&i.HomeDisplayName,
			&i.HomeShortDisplayName,
			&i.HomeColor,
			&i.HomeAlternateColor,
			&i.HomeIsActive,
			&i.HomeVenueID,
			&i.HomeLogo,
			&i.HomeScore,
			&i.HomeWinner,
			&i.AwayID,
			&i.AwayUid,
			&i.AwayLocation,
			&i.AwayName,
			&i.AwayAbbreviation,
			&i.AwayDisplayName,
			&i.AwayShortDisplayName,
			&i.AwayColor,
			&i.AwayAlternateColor,
			&i.AwayIsActive,
			&i.AwayVenueID,
			&i.AwayLogo,
			&i.AwayScore,
			&i.AwayWinner,
			&i.GameID,
			&i.Season,
			&i.SeasonType,
			&i.VenueAddressState,
			&i.StatusTypeAltDetail,
			&i.PBP,
			&i.TeamBox,
			&i.PlayerBox,
			&i.GameDateTime,
			&i.GameDate,
			&i.PlayByPlayAvailable,
			&i.Broadcast,
			&i.Highlights,
			&i.BroadcastMarket,
			&i.BroadcastName,
			&i.HomeLinescores,
			&i.HomeRecords,
			&i.AwayLinescores,
			&i.AwayRecords,
			&i.GameJson,
			&i.GameJsonUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
