// Code generated by sqlc. DO NOT EDIT.
// source: team_boxscore.sql

package db

import (
	"context"
)

const listTeamBoxscores = `-- name: ListTeamBoxscores :many
SELECT game_id, season, season_type, game_date, game_date_time, team_id, team_uid, team_slug, team_location, team_name, team_abbreviation, team_display_name, team_short_display_name, team_color, team_alternate_color, team_logo, team_home_away, team_score, team_winner, assists, blocks, defensive_rebounds, fast_break_points, field_goal_pct, field_goals_made, field_goals_attempted, flagrant_fouls, fouls, free_throw_pct, free_throws_made, free_throws_attempted, largest_lead, offensive_rebounds, points_in_paint, steals, team_turnovers, technical_fouls, three_point_field_goal_pct, three_point_field_goals_made, three_point_field_goals_attempted, total_rebounds, total_technical_fouls, total_turnovers, turnover_points, turnovers, opponent_team_id, opponent_team_uid, opponent_team_slug, opponent_team_location, opponent_team_name, opponent_team_abbreviation, opponent_team_display_name, opponent_team_short_display_name, opponent_team_color, opponent_team_alternate_color, opponent_team_logo, opponent_team_score FROM team_boxscores_raw
ORDER BY game_date DESC, game_id, team_id
LIMIT $1 OFFSET $2
`

type ListTeamBoxscoresParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTeamBoxscores(ctx context.Context, arg ListTeamBoxscoresParams) ([]TeamBoxscoresRaw, error) {
	rows, err := q.db.QueryContext(ctx, listTeamBoxscores, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamBoxscoresRaw
	for rows.Next() {
		var i TeamBoxscoresRaw
		if err := rows.Scan(
			&i.GameID,
			&i.Season,
			&i.SeasonType,
			&i.GameDate,
			&i.GameDateTime,
			&i.TeamID,
			&i.TeamUid,
			&i.TeamSlug,
			&i.TeamLocation,
			&i.TeamName,
			&i.TeamAbbreviation,
			&i.TeamDisplayName,
			&i.TeamShortDisplayName,
			&i.TeamColor,
			&i.TeamAlternateColor,
			&i.TeamLogo,
			&i.TeamHomeAway,
			&i.TeamScore,
			&i.TeamWinner,
			&i.Assists,
			&i.Blocks,
			&i.DefensiveRebounds,
			&i.FastBreakPoints,
			&i.FieldGoalPct,
			&i.FieldGoalsMade,
			&i.FieldGoalsAttempted,
			&i.FlagrantFouls,
			&i.Fouls,
			&i.FreeThrowPct,
			&i.FreeThrowsMade,
			&i.FreeThrowsAttempted,
			&i.LargestLead,
			&i.OffensiveRebounds,
			&i.PointsInPaint,
			&i.Steals,
			&i.TeamTurnovers,
			&i.TechnicalFouls,
			&i.ThreePointFieldGoalPct,
			&i.ThreePointFieldGoalsMade,
			&i.ThreePointFieldGoalsAttempted,
			&i.TotalRebounds,
			&i.TotalTechnicalFouls,
			&i.TotalTurnovers,
			&i.TurnoverPoints,
			&i.Turnovers,
			&i.OpponentTeamID,
			&i.OpponentTeamUid,
			&i.OpponentTeamSlug,
			&i.OpponentTeamLocation,
			&i.OpponentTeamName,
			&i.OpponentTeamAbbreviation,
			&i.OpponentTeamDisplayName,
			&i.OpponentTeamShortDisplayName,
			&i.OpponentTeamColor,
			&i.OpponentTeamAlternateColor,
			&i.OpponentTeamLogo,
			&i.OpponentTeamScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
